# Generated by Django 5.2.4 on 2025-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.PositiveIntegerField(blank=True, help_text='예 : 1기면 1', null=True, verbose_name='기수'),
        ),
    ]
