# Generated by Django 5.2.4 on 2025-08-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_wait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_wait',
        ),
    ]
