# Generated by Django 5.2.4 on 2025-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_is_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
