# Generated by Django 5.2.7 on 2025-12-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_can_use_gpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
