# Generated by Django 5.2.7 on 2026-04-20 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_profile_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_ua', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '비밀번호 재설정 토큰',
                'verbose_name_plural': '비밀번호 재설정 토큰 목록',
                'db_table': 'password_reset_token',
                'indexes': [models.Index(fields=['expires_at'], name='password_re_expires_214fae_idx'), models.Index(fields=['user', 'used_at'], name='password_re_user_id_145056_idx')],
            },
        ),
    ]
