# Generated by Django 5.2.7 on 2026-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserRefreshToken',
        ),
    ]
