# Generated by Django 5.2.13 on 2026-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_emailverificationcode_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_html',
            field=models.TextField(blank=True, default='', verbose_name='프로필 HTML'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('blocks', '블록'), ('html', 'HTML')], default='blocks', max_length=10, verbose_name='프로필 방식'),
        ),
    ]
