# Generated by Django 5.2.4 on 2025-07-28 12:32

import notions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TB', '교안'), ('NT', '공지')], default='TB', max_length=2, verbose_name='종류')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('html_content', models.FileField(upload_to=notions.models.file_upload_path, verbose_name='HTML 파일')),
                ('image', models.ImageField(upload_to=notions.models.file_upload_path, verbose_name='이미지 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '노션 콘텐츠',
                'verbose_name_plural': '노션 콘텐츠 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
