# Generated by Django 5.2.7 on 2026-02-02 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbig_backend', '0003_populate_jbig_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='팝업 제목')),
                ('content', models.TextField(verbose_name='팝업 내용')),
                ('start_date', models.DateTimeField(verbose_name='시작 일시')),
                ('end_date', models.DateTimeField(verbose_name='종료 일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '팝업',
                'verbose_name_plural': '팝업',
                'db_table': 'popups',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
