# Generated by Django 5.2.7 on 2026-03-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbig_backend', '0004_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 경로 (NCP key)'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='content',
            field=models.TextField(blank=True, verbose_name='팝업 내용'),
        ),
    ]
