# Generated by Codex on 2026-03-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_create_brag_board'),
        ('jbig_backend', '0005_popup_image_url_alter_popup_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='source_post',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='auto_popup',
                to='boards.post',
                verbose_name='원본 게시글'
            ),
        ),
    ]
