# Generated by Django 5.2.7 on 2026-01-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_serving', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notion',
            options={'verbose_name': '[Deprecated] Notion', 'verbose_name_plural': '[Deprecated] Notion'},
        ),
    ]
