# Generated by Django 5.2.7 on 2026-01-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuinstance',
            name='status',
            field=models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('terminated', 'Terminated')], default='starting', max_length=20),
        ),
    ]
