# Generated by Django 5.2.7 on 2026-03-24 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0034_board_available_tags_post_tag_alter_board_board_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruitment', serialize=False, to='boards.post', verbose_name='게시글')),
                ('recruitment_type', models.IntegerField(choices=[(1, '스터디'), (2, '경진대회'), (3, '프로젝트'), (4, '기타')], verbose_name='모집 유형')),
                ('status', models.IntegerField(choices=[(1, '모집중'), (2, '모집마감'), (3, '완료'), (4, '취소됨')], db_index=True, default=1, verbose_name='모집 상태')),
                ('max_members', models.PositiveIntegerField(default=0, help_text='0이면 인원 제한 없음', verbose_name='모집 인원')),
                ('deadline', models.DateTimeField(blank=True, db_index=True, help_text='null이면 상시모집', null=True, verbose_name='모집 마감일')),
                ('required_skills', models.JSONField(blank=True, default=list, verbose_name='필요 기술/조건')),
                ('contact_info', models.CharField(blank=True, help_text='수락된 지원자에게만 공개', max_length=200, verbose_name='연락처')),
                ('show_applicants', models.BooleanField(default=False, help_text='True이면 지원자끼리 서로의 이름·기수를 볼 수 있음', verbose_name='지원자 공개')),
                ('accepted_count', models.PositiveIntegerField(default=0, verbose_name='합류 확정 수')),
            ],
            options={
                'verbose_name': '모집',
                'verbose_name_plural': '모집 목록',
                'db_table': 'recruitment',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '대기중'), (2, '수락됨'), (3, '거절됨')], db_index=True, default=1, verbose_name='지원 상태')),
                ('message', models.TextField(blank=True, verbose_name='지원 메시지')),
                ('recruiter_note', models.TextField(blank=True, help_text='모집자만 볼 수 있는 내부 메모', verbose_name='모집자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitments.recruitment', verbose_name='모집')),
            ],
            options={
                'verbose_name': '지원',
                'verbose_name_plural': '지원 목록',
                'db_table': 'application',
                'ordering': ['-created_at'],
                'unique_together': {('recruitment', 'applicant')},
            },
        ),
    ]
