# Generated by Django 5.2.4 on 2025-08-09 06:14

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.FileField(blank=True, null=True, upload_to=boards.models.post_upload_path),
        ),
    ]
