# Generated by Django 5.2.4 on 2025-08-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Staff Only'), (3, 'Justification Letter')], default=1),
        ),
    ]
