# Generated by Django 5.2.4 on 2025-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='comment_permission',
            field=models.CharField(choices=[('all', 'All'), ('staff', 'Staff')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='read_permission',
            field=models.CharField(choices=[('all', 'All'), ('staff', 'Staff')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='write_permission',
            field=models.CharField(choices=[('all', 'All'), ('staff', 'Staff')], default='all', max_length=10),
        ),
    ]
