# Generated by Django 5.2.4 on 2025-08-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_comment_permission_board_read_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='write_permission',
            new_name='post_permission',
        ),
    ]
