# Generated by Django 5.2.4 on 2025-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_rename_write_permission_board_post_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Admin'), (3, 'Justification')], default=1),
        ),
    ]
