# Generated by Django 5.2.4 on 2025-08-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_board_board_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': [('can_read_board', 'Can read posts on this board'), ('can_write_post', 'Can write posts on this board'), ('can_comment_post', 'Can comment on posts on this board')], 'verbose_name': '게시판', 'verbose_name_plural': '게시판 목록'},
        ),
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Admin'), (3, 'Reason')], default=1),
        ),
    ]
