# Generated by Django 5.2.4 on 2025-09-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_alter_board_options_alter_board_board_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판 목록'},
        ),
    ]
