# Generated by Django 5.2.4 on 2025-09-06 04:29

import os
from django.db import migrations
from django.contrib.postgres.search import SearchVector
from django.db.models import Value
from bs4 import BeautifulSoup

def populate_search_vector(apps, schema_editor):
    Post = apps.get_model('boards', 'Post')
    for post in Post.objects.all():
        content_text = ''
        if post.content_html and hasattr(post.content_html, 'path') and os.path.exists(post.content_html.path):
            try:
                with open(post.content_html.path, 'r', encoding='utf-8') as f:
                    soup = BeautifulSoup(f, 'html.parser')
                    content_text = soup.get_text()
            except (FileNotFoundError, Exception):
                content_text = ''
        
        post.search_vector = SearchVector('title', weight='A') + SearchVector(Value(content_text), weight='B')
        post.save(update_fields=['search_vector'])

class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_post_search_vector_post_post_search__c2a177_idx'),
    ]

    operations = [
        migrations.RunPython(populate_search_vector, migrations.RunPython.noop),
    ]