# Generated by Django 5.2.4 on 2025-09-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20250906_1329'),
    ]

    operations = [
    ]
