# Generated by Django 5.2.4 on 2025-09-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20250906_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('board', 'board_post_id')},
        ),
    ]
