# Generated by Django 5.2.4 on 2025-09-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_post_board_post_id_alter_post_unique_together'),
    ]

    operations = [
    ]
