# Generated by Django 5.2.4 on 2025-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_populate_board_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Admin'), (3, 'Justification Letter')], default=1),
        ),
    ]
