# Generated by Django 5.2.7 on 2025-10-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_alter_board_board_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
