# Generated by Django 5.2.7 on 2025-10-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_alter_post_content_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment_paths',
            field=models.JSONField(blank=True, default=list, help_text='첨부파일 경로 목록'),
        ),
    ]
