# Generated by Django 5.2.7 on 2025-10-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_remove_attachment_post_post_attachment_paths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_html',
            new_name='content_md',
        ),
    ]
