# Generated by Django 5.2.7 on 2025-10-25 15:50

import boards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0020_rename_content_html_post_content_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='boards.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.FileField(blank=True, null=True, upload_to=boards.models.post_upload_path),
        ),
    ]
