# Generated by Django 5.2.7 on 2025-10-25 16:04
# (데이터 복사 스크립트로 수정됨)

from django.db import migrations
import html2text # HTML -> Markdown 변환기
import os # 파일 경로 확인용

# --- 5단계의 핵심: 데이터 복사 함수 ---
def migrate_data(apps, schema_editor):
    Post = apps.get_model('boards', 'Post')
    Attachment = apps.get_model('boards', 'Attachment') 
    
    # html2text 변환기 설정
    h = html2text.HTML2Text()
    h.ignore_links = False # 링크도 변환
    h.ignore_images = False # 이미지도 변환

    print("\n[  5단계: 데이터 복사 마이그레이션 시작 ]")
    
    # .iterator()를 써서 메모리를 아끼며 모든 게시글을 순회합니다.
    for post in Post.objects.all().iterator():
        
        # --- 1. 컨텐츠 복사 (HTML File -> MD Text) ---
        try:
            # content_html 필드에 파일이 있고 (None이나 ""이 아니고)
            if post.content_html and post.content_html.name:
                # 그 파일이 실제로 서버에 존재하는지 확인
                if post.content_html.storage.exists(post.content_html.name):
                    # 파일을 열어서 HTML 내용을 읽어옴
                    with post.content_html.open('r') as f:
                        html_content = f.read()
                    
                    # HTML -> Markdown 변환!
                    post.content_md = h.handle(html_content)
                else:
                    # 파일 경로는 있는데, 실제 파일이 없는 경우
                    print(f"  - 경고: Post {post.id}의 content_html 파일({post.content_html.name})을 찾을 수 없습니다.")
                    post.content_md = "" # 빈 텍스트로 처리
            else:
                # content_html 필드 자체가 비어있는 경우 (예: 옛날 글)
                post.content_md = "" # 빈 텍스트로 처리
        
        except Exception as e:
            print(f"  - 오류: Post {post.id} 컨텐츠 변환 중 오류 발생: {e}")
            post.content_md = "" # 오류 시에도 빈 텍스트로 처리

        
        # --- 2. 첨부파일 복사 (Attachment FK -> JSONField) ---
        # "post=post"는 Attachment 모델의 'post' 필드를 의미 (아까 부활시킨 것)
        old_attachments = Attachment.objects.filter(post=post)
        
        new_paths_list = []
        for att in old_attachments:
            # Attachment 모델의 'file' 필드와 'filename' 필드 사용
            if att.file and att.filename:
                new_paths_list.append({
                    "url": att.file.url, 
                    "name": att.filename
                })
        
        # 변환된 리스트를 JSON 필드에 저장
        post.attachment_paths = new_paths_list
        
        # --- 3. DB에 최종 저장 ---
        # update_fields를 사용해 이 2개 필드만 정확히 업데이트
        post.save(update_fields=['content_md', 'attachment_paths'])

    print("[ ✅ 5단계: 데이터 복사 완료 ]")


# --- Django가 이 함수를 실행하도록 등록 ---
class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_attachment_post_post_content_html'),
    ]

    operations = [
        # 이 마이그레이션을 실행할 때, "migrate_data" 함수를 실행해줘!
        migrations.RunPython(migrate_data),
    ]
