# Generated by Django 5.2.7 on 2025-10-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0022_copy_old_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_html',
        ),
    ]
