# Generated by Django 5.2.7 on 2025-11-25 14:29

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_remove_attachment_post_remove_post_content_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '[Deprecated] 첨부파일', 'verbose_name_plural': '[Deprecated] 첨부파일'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_search__c2a177_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='post_search__a12f1d_gin'),
        ),
    ]
