# Generated by Django 5.2.7 on 2025-12-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_notification_table_if_not_exists(apps, schema_editor):
    """notification 테이블이 없으면 생성"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS notification (
                id BIGSERIAL PRIMARY KEY,
                notification_type INTEGER NOT NULL,
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                actor_id BIGINT NOT NULL REFERENCES users_user(id) ON DELETE CASCADE,
                recipient_id BIGINT NOT NULL REFERENCES users_user(id) ON DELETE CASCADE,
                post_id BIGINT NOT NULL REFERENCES post(id) ON DELETE CASCADE,
                comment_id BIGINT NULL REFERENCES comment(id) ON DELETE CASCADE
            );
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS notification_recipient_id_idx ON notification(recipient_id);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS notification_actor_id_idx ON notification(actor_id);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS notification_post_id_idx ON notification(post_id);
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS notification_comment_id_idx ON notification(comment_id);
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_commentlike_comment_likes_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_notification_table_if_not_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('notification_type', models.IntegerField(choices=[(1, '댓글'), (2, '대댓글'), (3, '좋아요'), (4, '댓글 좋아요')], verbose_name='알림 유형')),
                        ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='알림 발생시킨 사용자')),
                        ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='boards.comment', verbose_name='관련 댓글')),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='boards.post', verbose_name='관련 게시글')),
                        ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='알림 받는 사용자')),
                    ],
                    options={
                        'verbose_name': '알림',
                        'verbose_name_plural': '알림 목록',
                        'db_table': 'notification',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
    ]

