# Generated by Django 5.2.7 on 2025-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_commentlike_comment_likes_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, '댓글'), (2, '대댓글'), (3, '좋아요'), (4, '댓글 좋아요')], verbose_name='알림 유형'),
        ),
    ]
