# Generated by Django 5.2.7 on 2025-12-15 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0026_notification'),
        ('users', '0014_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='draft_buffer', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('content_md', models.TextField(blank=True, verbose_name='내용')),
                ('uploaded_paths', models.JSONField(blank=True, default=list, help_text='업로드된 파일 경로 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='boards.board', verbose_name='게시판')),
            ],
            options={
                'verbose_name': '게시글 작성 버퍼',
                'verbose_name_plural': '게시글 작성 버퍼 목록',
                'db_table': 'draft',
                'ordering': ['-updated_at'],
            },
        ),
    ]
