# Generated by Django 5.2.7 on 2026-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0027_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='익명 작성 여부'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='익명 작성 여부'),
        ),
    ]
