# Generated by Django 5.2.7 on 2026-03-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0033_alter_comment_author_alter_notification_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='available_tags',
            field=models.JSONField(blank=True, default=list, help_text='예: ["팀원모집", "후기", "정보공유", "질문"]', verbose_name='사용 가능한 태그'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='글 태그'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Admin'), (3, 'Justification Letter'), (4, 'Photo Album')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, '댓글'), (2, '대댓글'), (3, '좋아요'), (4, '댓글 좋아요'), (5, '지원 접수'), (6, '지원 수락'), (7, '지원 거절'), (8, '모집 마감')], verbose_name='알림 유형'),
        ),
    ]
