# Generated by Codex on 2026-03-28

from django.db import migrations


def create_brag_board(apps, schema_editor):
    Category = apps.get_model('boards', 'Category')
    Board = apps.get_model('boards', 'Board')

    # 완전 초기 DB에서는 seed_data가 전체 게시판을 생성하므로 여기서는 생성하지 않음
    if Board.objects.count() == 0:
        return

    category, _ = Category.objects.get_or_create(name='커뮤니티')

    board, created = Board.objects.get_or_create(
        name='자랑게시판',
        defaults={
            'category': category,
            'board_type': 1,  # GENERAL
            'read_permission': 'all',
            'post_permission': 'all',
            'comment_permission': 'all',
            'available_tags': [],
        }
    )

    if created:
        return

    changed = False
    if board.category_id != category.id:
        board.category_id = category.id
        changed = True
    if board.board_type != 1:
        board.board_type = 1
        changed = True
    if board.read_permission != 'all':
        board.read_permission = 'all'
        changed = True
    if board.post_permission != 'all':
        board.post_permission = 'all'
        changed = True
    if board.comment_permission != 'all':
        board.comment_permission = 'all'
        changed = True

    if list(board.available_tags or []):
        board.available_tags = []
        changed = True
    if changed:
        board.save(update_fields=[
            'category', 'board_type', 'read_permission', 'post_permission',
            'comment_permission', 'available_tags'
        ])


def noop_reverse(apps, schema_editor):
    # 운영 중 데이터는 보존합니다.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0034_board_available_tags_post_tag_alter_board_board_type_and_more'),
    ]

    operations = [
        migrations.RunPython(create_brag_board, noop_reverse),
    ]
