# Generated by Codex on 2026-03-28

from django.db import migrations


def clear_brag_board_tags(apps, schema_editor):
    Board = apps.get_model('boards', 'Board')
    Board.objects.filter(name='자랑게시판').update(available_tags=[])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0035_create_brag_board'),
    ]

    operations = [
        migrations.RunPython(clear_brag_board_tags, noop_reverse),
    ]
