# Generated by Django 5.2.13 on 2026-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0039_backfill_board_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_site_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='form_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Absence'), (2, 'Feedback'), (3, 'Link Share')], default=0, help_text='작성 화면에서 띄울 입력 폼. 권한(board_type)과 별개로 동작한다.', verbose_name='작성 폼 종류'),
        ),
    ]
