# Generated by Django 5.2.13 on 2026-07-05 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0043_remove_link_share_board"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="form_type",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Absence"), (2, "Feedback")],
                default=0,
                help_text="작성 화면에서 띄울 입력 폼. 권한(board_type)과 별개로 동작한다.",
                verbose_name="작성 폼 종류",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"], name="notif_recipient_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["board", "-created_at"], name="post_board_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["board", "tag", "-created_at"],
                name="post_board_tag_created_idx",
            ),
        ),
    ]
