# Generated by Django 5.2.13 on 2026-07-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0046_remove_link_share_form_type_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="comment_permission",
            field=models.CharField(
                choices=[("all", "All"), ("member", "Member"), ("staff", "Staff")],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="post_permission",
            field=models.CharField(
                choices=[("all", "All"), ("member", "Member"), ("staff", "Staff")],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="read_permission",
            field=models.CharField(
                choices=[("all", "All"), ("member", "Member"), ("staff", "Staff")],
                default="all",
                max_length=10,
            ),
        ),
    ]
